version: "3.9"

services:
  qr-service:
    build: .
    container_name: qr-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - eciexpress-network

networks:
  eciexpress-network:
    driver: bridge
